### ISSUE TITLE
Need configuration help

### ISSUE THREAD

**Issue by jlearman** [PRATAP-KUMAR/replace-activities-text#8]
After installing replace-activities-text via the GNOME Shell Extensions web page, I see the new text in the upper left hand corner, but I don't know how to open the control panel to change it.

I tried some guesswork but no luck:
```
Mar/08-13:21:47:~$ gnome-extensions prefs replace-activities-text
Extension ?replace-activities-text? doesn't exist
Mar/08-13:21:51:~$ gnome-extensions list                         
ding@rastersoft.com
ubuntu-appindicators@ubuntu.com
ubuntu-dock@ubuntu.com
replaceActivitiesText@pratap.fastmail.fm
```

This is Ubuntu 22.04 LTS with Gnome Shell 42.9

**Comment by pratap-panabaka** [comment]
`gnome-extensions prefs replaceActivitiesText@pratap.fastmail.fm` the required argument is UUID of the extension which is `replaceActivitiesText@pratap.fastmail.fm`

**Comment by pratap-panabaka** [comment]
Hi @jlearman its 12AM for me on March 9th. I am about to sleep but can help you from mobile for another 30minutes.

**Comment by jlearman** [comment]
Thanks that worked, done here, go to sleep!
