### ISSUE TITLE
Please gnome 46!

### ISSUE THREAD

**Issue by alisson3000br** [PRATAP-KUMAR/replace-activities-text#9]
Please make it gnome 46 i'm begging you hahaahahaha

**Comment by pratap-panabaka** [comment]
Hi

https://extensions.gnome.org/extension/6272/add-custom-text-to-workspace-indicators/

**Comment by alisson3000br** [comment]
Hi thanks for reply
I tried, I updated to ubuntu 24 and had to uninstal this extension and install add custom text but it gives an error. is it because there is kind of a cache of the replace activities extension and it is conflicting with the add custom text
![Screenshot from 2024-05-20 19-34-37](https://github.com/PRATAP-KUMAR/replace-activities-text/assets/148722558/3d337a70-53b2-4454-90d2-6b9596eb4ecc)

**Comment by alisson3000br** [comment]
im trying but no success, please help

thanks in advance

**Comment by pratap-panabaka** [comment]
Hi I just check the extension in Ubuntu 24.04 and it is working fine. I uninstalled the same from my system and installed the official extension from gnome-extensions. I didn't see any error. How did you install the extension? Via downloading or Browser extension?

**Comment by alisson3000br** [comment]
i installed by the gnome extensions website and tried the downloaded the .zip file from github

**Comment by pratap-panabaka** [comment]
I was trying the extension from the beginning of Ubuntu 24.04 frequently like from beta release and never face issue. May be a point release like 24.04.x has some issues. The error message from your screenshot is understandable. May be after a update of your Ubuntu 24.04 may resolve it.

Thanks

**Comment by alisson3000br** [comment]
the error i dont know what pill is undefined means

**Comment by pratap-panabaka** [comment]
It is related to extension code. The "pill" is small dots which indicates how many work spaces are there and which one is active. I am sure after your Ubuntu OS update, It should work. Upgrading Ubuntu from version to version have slight issues like this.

**Comment by alisson3000br** [comment]
i will format the pc do a clean install, i booted from the usb and installed the extension succesfully, there is something with my current OS that gives that error

**Comment by pratap-panabaka** [comment]
I will update now and see if I am getting that error.

![image](https://github.com/PRATAP-KUMAR/replace-activities-text/assets/40719899/34f6abf2-b6f7-4e8d-98fb-f1a05af0af80)

![image](https://github.com/PRATAP-KUMAR/replace-activities-text/assets/40719899/488e4854-66cf-4bc5-bbe7-9eff24da63b6)

**Comment by pratap-panabaka** [comment]
Hi, After update/upgrade, still the extension is working fine. I am sorry about the issue you are facing and not being able to help.

Thanks.

**Comment by alisson3000br** [comment]
no problem  my system deserves a fresh install anyways 
thank you

**Comment by PRATAP-KUMAR** [comment]
Oh ok.
May I know from which country are you?
